"""
Prompts module for the Self-Foveate framework.

This module aggregates all prompt templates for backward compatibility
and easy access from a single import point.
"""

# Task generation prompts
from self_foveate.prompts.task import (
    generate_generation_json,
    READING_COMPREHENSION_SYSTEM_PROMPT,
    READING_COMPREHENSION_USER_PROMPT,
    REREADING_SYSTEM_PROMPT,
    REREADING_USER_PROMPT,
)

# Scatter (Core) strategy prompts - new names
from self_foveate.prompts.scatter import (
    SCATTER_IMPORTANT_SYSTEM_PROMPT,
    SCATTER_IMPORTANT_USER_PROMPT,
    SCATTER_KEYWORDS_SYSTEM_PROMPT,
    SCATTER_KEYWORDS_USER_PROMPT,
    SCATTER_GENERATION_SYSTEM_PROMPT,
    SCATTER_GENERATION_USER_PROMPT,
    SCATTER_REGENERATION_SYSTEM_PROMPT,
    SCATTER_REGENERATION_USER_PROMPT,
)


# Micro (Word) strategy prompts - new names
from self_foveate.prompts.micro import (
    MICRO_KEYWORDS_SYSTEM_PROMPT,
    MICRO_KEYWORDS_USER_PROMPT,
    MICRO_GENERATION_SYSTEM_PROMPT,
    MICRO_GENERATION_USER_PROMPT,
    MICRO_REGENERATION_SYSTEM_PROMPT,
    MICRO_REGENERATION_USER_PROMPT,
)


# Macro (Sentence) strategy prompts - new names
from self_foveate.prompts.macro import (
    MACRO_KEYWORDS_SYSTEM_PROMPT,
    MACRO_KEYWORDS_USER_PROMPT,
    MACRO_GENERATION_SYSTEM_PROMPT,
    MACRO_GENERATION_USER_PROMPT,
    MACRO_REGENERATION_SYSTEM_PROMPT,
    MACRO_REGENERATION_USER_PROMPT,
)


__all__ = [
    # Task generation
    "generate_generation_json",
    "READING_COMPREHENSION_SYSTEM_PROMPT",
    "READING_COMPREHENSION_USER_PROMPT",
    "REREADING_SYSTEM_PROMPT",
    "REREADING_USER_PROMPT",
    # Scatter strategy (new names)
    "SCATTER_IMPORTANT_SYSTEM_PROMPT",
    "SCATTER_IMPORTANT_USER_PROMPT",
    "SCATTER_KEYWORDS_SYSTEM_PROMPT",
    "SCATTER_KEYWORDS_USER_PROMPT",
    "SCATTER_GENERATION_SYSTEM_PROMPT",
    "SCATTER_GENERATION_USER_PROMPT",
    "SCATTER_REGENERATION_SYSTEM_PROMPT",
    "SCATTER_REGENERATION_USER_PROMPT",
    # Micro strategy (new names)
    "MICRO_KEYWORDS_SYSTEM_PROMPT",
    "MICRO_KEYWORDS_USER_PROMPT",
    "MICRO_GENERATION_SYSTEM_PROMPT",
    "MICRO_GENERATION_USER_PROMPT",
    "MICRO_REGENERATION_SYSTEM_PROMPT",
    "MICRO_REGENERATION_USER_PROMPT",
    # Macro strategy (new names)
    "MACRO_KEYWORDS_SYSTEM_PROMPT",
    "MACRO_KEYWORDS_USER_PROMPT",
    "MACRO_GENERATION_SYSTEM_PROMPT",
    "MACRO_GENERATION_USER_PROMPT",
    "MACRO_REGENERATION_SYSTEM_PROMPT",
    "MACRO_REGENERATION_USER_PROMPT",
]
